### ISSUE TITLE
Code rendering has extra newlines in jekyll 3--ugly without linenos, unusable with linenos

### ISSUE THREAD

**Issue by edruder** [poole/poole#147]
The following sample post containing two code blocks illustrates a bug.

```
---
layout: post
title: Example content
---

### Code

Inline code is available with the `<code>` element. Snippets of multiple lines of code are supported through Pygments. Longer lines will automatically scroll horizontally when needed.

{% highlight js %}
// Example can be run directly in your JavaScript console

// Create a function that takes two arguments and returns the sum of those arguments
var adder = new Function("a", "b", "return a + b");

// Call the function
adder(2, 6);
// > 8
{% endhighlight %}

You may also optionally show code snippets with line numbers. Add `linenos` to the Pygments tags.

{% highlight js linenos %}
// Example can be run directly in your JavaScript console

// Create a function that takes two arguments and returns the sum of those arguments
var adder = new Function("a", "b", "return a + b");

// Call the function
adder(2, 6);
// > 8
{% endhighlight %}

Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.
```

In a new `jekyll` 3.3.1 project, the code is rendered decently:

![jekyll](https://cloud.githubusercontent.com/assets/3007/20589931/7f05f440-b1d4-11e6-882c-4a3ef629e945.png)

In a new Poole project (after correcting the permalink issue), the code is rendered badly:

![Poole](https://cloud.githubusercontent.com/assets/3007/20590131/1bdc2d74-b1d6-11e6-9885-cef2fdae93f2.png)

The "bad"/`poole` page source has extra newlines at the end of the comment lines, inside the `<span>` elements, which causes some/all of the problem.

I don't know how `jekyll`/`rouge`/`poole` interact, s.t. plain `jekyll` works correctly (with no extra newlines inside the `<span>`s) and `poole` gets extraneous newlines, which mess up the formatting.

This problem makes Poole pretty unusable for a technical blog.

**Comment by HiroAgustin** [comment]
By applying the changes from PR #139 and wrapping the base table styles in a `.table` class, the result matches the original design.

The trade off is having to add a class name whenever a table is needed.

**Comment by kidkkr** [comment]
I've fixed it by doing this:
1. install pygments `$ gem install pygments`.
2. add explicit config for `pygments` in `/_config.yml`.
```
highlighter: pygments
```

**Comment by verificationcontractor** [comment]
I have the same problem in a similar project. Did anyone find a solution?

**Comment by HiroAgustin** [comment]
> I have the same problem in a similar project. Did anyone find a solution?

Yes, https://github.com/poole/poole/issues/147#issuecomment-358664157

**Comment by mrpandey** [comment]
Thanks @HiroAgustin. Adding `figure {margin: 0;}` to poole.css solved the margin issue. But the problem with extra new lines still exists. I commented out the `table` styles in poole.css but extra newline are still there.

**Comment by mdo** [comment]
This was indeed a line ending issue. Fixed in `master`.
